Added source to .etym as per #343
snoonetIRC/CloudBot pull request #354
Opened 2019-01-24 15:35 UTC by nekosune

2019-01-24 15:40 UTC, linuxdaemon requested changes

2019-01-24 15:40 UTC, linuxdaemon commented on plugins/etymology.py
> +        etym = etym[:etym.rfind(' ', 0, 200)] + ' ...'
Please replace this with `truncate()` from `cloudbot.util.formatting`

2019-01-24 15:40 UTC, linuxdaemon commented on plugins/etymology.py
> +    etym = etym + " Source: " + response.url
```suggestion
    etym += " Source: " + response.url
```

2019-01-24 15:40 UTC, linuxdaemon commented on plugins/etymology.py
> +            return 'No etymology found for {} :('.format(text)
```suggestion
            return "No etymology found for {} :(".format(text)
```
Text presented to the user should be enclosed in double quotes

2019-01-24 15:40 UTC, linuxdaemon commented on plugins/etymology.py
> +        if response.status_code == 404:
It may be better to use `e.response` like the `reply()` line below does

2019-01-24 15:48 UTC, linuxdaemon commented
Please add a `Fixes <issue>` line to the PR description so GitHub will auto close it

2019-01-24 16:40 UTC, linuxdaemon approved these changes

2019-01-24 16:41 UTC, linuxdaemon requested changes

2019-01-24 16:41 UTC, linuxdaemon commented on plugins/etymology.py
There should be 2 blank lines before and after a function

2019-01-25 01:24 UTC, linuxdaemon requested changes

2019-01-25 01:24 UTC, linuxdaemon commented on plugins/etymology.py
> +    etym += " Source: " + response.url
Wrapping `response.url` in `web.try_shorten()` would make it more consistent with other commands

2019-01-25 13:42 UTC, nekosune commented on plugins/etymology.py
> +    etym += " Source: " + response.url
This should do it
```suggestion
    etym += " Source: " + web.try_shorten(response.url)
```

2019-01-25 17:48 UTC, linuxdaemon approved these changes

2019-01-25 17:48 UTC, merged