Various maintainability fixes/cleanup, prompted by CodeFacter
snoonetIRC/CloudBot pull request #377
Opened 2019-02-02 07:17 UTC by linuxdaemon

2019-02-03 04:19 UTC, A-UNDERSCORE-D requested changes
Switch the quoting to be consistent, I believe the preferred method is single quotes for non-user-facing strings and double quotes otherwise, excluding docstrings

2019-02-03 04:42 UTC, A-UNDERSCORE-D submitted a review, later dismissed

2019-02-04 06:40 UTC, A-UNDERSCORE-D submitted a review, later dismissed

2019-02-04 15:09 UTC, GaeaKat approved these changes

2019-02-05 02:34 UTC, leonthemisfit approved these changes
I demand GitLab back so I can leave my emoji based code reviews!

2019-02-05 02:36 UTC, merged