Refactor duckhunt .killers/.friends commands
snoonetIRC/CloudBot pull request #496
Opened 2019-04-19 17:32 UTC by linuxdaemon

Move all common code to a central function

Fix issues in certain error responses

2019-04-25 03:35 UTC, A-UNDERSCORE-D requested changes

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on plugins/duckhunt.py
> +from time import sleep, time
....why?

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on plugins/duckhunt.py
> +duck = [
Own PR for cleanup

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on plugins/duckhunt.py
> +                self.game_on and self.duck_status == 0 and
Own PR for cleanup

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +    assert repr(
Use variables instead. This is a mess to read

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +    assert duckhunt.get_channel_scores(
Use variables instead. This is a mess to read

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +    assert repr(
Use variables instead. This is a mess to read

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +    assert repr(
Use variables instead. This is a mess to read

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +    assert repr(
Use variables instead. This is a mess to read

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +    assert repr(
Use variables instead. This is a mess to read

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +    assert repr(
Use variables instead. This is a mess to read

2019-04-25 03:35 UTC, A-UNDERSCORE-D commented on tests/plugin_tests/test_duckhunt.py
> +            'Duck friend scores in #TestChannel: ',
Indentation looks weird here

2019-04-25 15:18 UTC, linuxdaemon commented on plugins/duckhunt.py
> +from time import sleep, time
pycharm import organization

2019-04-29 00:56 UTC, A-UNDERSCORE-D approved these changes

2019-04-29 02:05 UTC, merged