Update tea.json
snoonetIRC/CloudBot pull request #577
Opened 2019-08-03 21:29 UTC by jaco1982

Updated teas with new actions, temperatures, sizes and teas

2019-08-03 21:34 UTC, RhinosF1 approved these changes
Nice!

2019-08-03 21:37 UTC, A-UNDERSCORE-D requested changes
Please reindent file with four spaces per indent level

2019-08-05 10:33 UTC, RhinosF1 approved these changes

2019-08-05 10:42 UTC, jaco1982 commented
OK, there was a conflict, which stopped the commit from going through. I suspect I might have resolved the conflict in the wrong direction. I'm going to close this PR, get this file formatted properly and will submit a new PR then.

2019-08-05 10:42 UTC, closed without merging