add squid module
snoonetIRC/CloudBot pull request #600
Opened 2019-08-28 21:11 UTC by RhinosF1

2019-08-28 21:14 UTC, A-UNDERSCORE-D commented on data/food/squid.json
> +        "part: [
Missing quote

2019-08-28 21:14 UTC, linuxdaemon requested changes

2019-08-28 21:14 UTC, linuxdaemon commented on plugins/foods.py
> +    BasicFood("squid", "squid")
```suggestion
    BasicFood("squid", "squid"),
```

2019-08-28 21:14 UTC, linuxdaemon commented on data/food/squid.json
> +        "part: [
```suggestion
        "part": [
```

2019-08-28 23:40 UTC, linuxdaemon requested changes

2019-08-28 23:40 UTC, linuxdaemon commented on plugins/foods.py
> +    BasicFood("squid", "squid"),
```suggestion
    BasicFood("squid", "some squid"),
```
So it will say ".squid - Serves <user> some squid", "I can't serve some squid to that user", etc

2019-09-02 12:23 UTC, linuxdaemon approved these changes

2019-09-02 12:24 UTC, merged